# Copyright (c) 2014, Ruslan Baratov
# Copyright (c) 2014, 2016 Alexander Lamaison
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      OPENSSL: "111"
      BUILD_SHARED_LIBS: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      OPENSSL: "111"
      BUILD_SHARED_LIBS: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      OPENSSL: "111"
      BUILD_SHARED_LIBS: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      OPENSSL: "111"
      BUILD_SHARED_LIBS: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 11 2012"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 11 2012"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: OFF

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 9 2008"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: ON

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 9 2008"
      OPENSSL: "102"
      BUILD_SHARED_LIBS: OFF

  digitalocean_access_token:
    secure: 8qRitvrj69Xhf0Tmu27xnz5drmL2YhmOJLGpXIkYyTCC0JNtBoXW6fMcF3u4Uj1+pIQ+TjegQOwYimlz0oivKTro3v3EXro+osAMNJG6NKc=

platform:
  - x86
  - x64

configuration:
# - Debug
# - Release
  - RelWithDebInfo

matrix:
  fast_finish: false
  allow_failures:
    - GENERATOR: "Visual Studio 9 2008"
      platform: x64

install:
  - choco install -y docker
  - choco install -y docker-machine
  - ps: if($env:GENERATOR -eq "Visual Studio 15 2017") { $env:VC_VERSION="VC15" }
  - ps: if($env:GENERATOR -eq "Visual Studio 14 2015") { $env:VC_VERSION="VC14" }
  - ps: if($env:GENERATOR -eq "Visual Studio 11 2012") { $env:VC_VERSION="VC11" }
  - ps: if($env:GENERATOR -eq "Visual Studio 9 2008") { $env:VC_VERSION="VC9" }
  - cmd: call vstudio.bat %VC_VERSION% %platform%

build_script:
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GEN_SUFFIX=" Win64" }
  - ps: if($env:BUILD_SHARED_LIBS -eq "ON") { $env:ZIP_SUFFIX="-dll" }
  - ps: if($env:BUILD_SHARED_LIBS -eq "OFF") { $env:ZIP_SUFFIX="-lib" }
  - ps: if($env:OPENSSL -eq "111" -And $env:PLATFORM -eq "x64") { $env:OPENSSL_ROOT_DIR="C:\OpenSSL-v111-Win64" }
  - ps: if($env:OPENSSL -eq "111" -And $env:PLATFORM -eq "x86") { $env:OPENSSL_ROOT_DIR="C:\OpenSSL-v111-Win32" }
  - ps: if($env:OPENSSL -eq "102" -And $env:PLATFORM -eq "x64") { $env:OPENSSL_ROOT_DIR="C:\OpenSSL-Win64" }
  - ps: if($env:OPENSSL -eq "102" -And $env:PLATFORM -eq "x86") { $env:OPENSSL_ROOT_DIR="C:\OpenSSL-Win32" }
  - cmake "-G%GENERATOR%%CMAKE_GEN_SUFFIX%" -DOPENSSL_ROOT_DIR=%OPENSSL_ROOT_DIR% -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% -H. -B_builds
  - cmake --build _builds --config "%CONFIGURATION%" || exit /b 0
  - if exist _builds\src\%CONFIGURATION%\libssh2.lib cd _builds\src\%CONFIGURATION%
  - if not exist libssh2.pdb if exist ..\libssh2.dir\%CONFIGURATION%\libssh2.pdb copy ..\libssh2.dir\%CONFIGURATION%\libssh2.pdb .
  - dir
  - if exist libssh2.lib 7z a ..\..\..\LibSSH2-%VC_VERSION%-%platform%-OpenSSL%OPENSSL%%ZIP_SUFFIX%.zip .
  - if exist libssh2.lib cd ..\..\..

artifacts:
  - path: "*.zip"

before_test:
  - set DOCKER_MACHINE_NAME=appveyor-%APPVEYOR_PROJECT_SLUG%-%APPVEYOR_JOB_ID%
  - ps: if($env:digitalocean_access_token) { echo "Using DigitalOcean for testing." } else { echo "DigitalOcean not available. Skipping testing." }
  - ps: if($env:digitalocean_access_token) { docker-machine create --driver digitalocean --digitalocean-access-token $($env:digitalocean_access_token) $($env:DOCKER_MACHINE_NAME) }
  - ps: if($env:digitalocean_access_token) { docker-machine env $($env:DOCKER_MACHINE_NAME) --shell powershell | Invoke-Expression }

test_script:
  - ps: cd _builds
  - ps: if($env:digitalocean_access_token) { ctest -VV -C $($env:CONFIGURATION) --output-on-failure }

after_test:
  - ps: if($env:digitalocean_access_token) { docker-machine rm -y $($env:DOCKER_MACHINE_NAME) }

on_failure:
  - ps: if($env:digitalocean_access_token) { docker-machine rm -y $($env:DOCKER_MACHINE_NAME) }
  - ps: if(Test-Path _builds/CMakeFiles/CMakeOutput.log) { cat _builds/CMakeFiles/CMakeOutput.log }
  - ps: if(Test-Path _builds/CMakeFiles/CMakeError.log) { cat _builds/CMakeFiles/CMakeError.log }

  # whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master
        - 1.8.x
